# Generated by Django 5.0.4 on 2024-05-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_phone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='narxi',
            field=models.IntegerField(default=0),
        ),
    ]
