# Generated by Django 5.0.4 on 2024-05-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_phone_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='rangi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
