# Generated by Django 5.0.4 on 2024-05-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_phone_rangi'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='holati',
            field=models.CharField(choices=[('kelishiladi', 'kelishiladi'), ('barter', 'barter'), ('tekin', 'tekin')], default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='xotira',
            field=models.CharField(choices=[('8 GB', '8GB'), ('16 GB', '16GB'), ('32 GB', '32GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB')], default=0, max_length=50),
        ),
    ]
