# Generated by Django 5.0.4 on 2024-05-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_phone_holati_phone_xotira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='holati',
            field=models.CharField(choices=[('kelishiladi', 'kelishiladi'), ('barter', 'barter'), ('tekin', 'tekin'), ('naxt', 'naxt')], default='naxt', max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='rangi',
            field=models.CharField(choices=[('black', 'black'), ('titanium', 'titanium'), ('pink', 'pink'), ('yellow', 'yellow'), ('grey', 'grey'), ('blue', 'blue')], max_length=50, null=True),
        ),
    ]
