# Generated by Django 5.0.4 on 2024-05-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_phone_holati_alter_phone_rangi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='rangi',
            field=models.CharField(choices=[('black', 'black'), ('titanium', 'titanium'), ('pink', 'pink'), ('yellow', 'yellow'), ('grey', 'grey'), ('blue', 'blue'), ('white', 'white')], default='rang tanlang', max_length=50, null=True),
        ),
    ]
